export const SOURCE_UPDATED = 'SOURCE_UPDATED';
export const COMPILE_SOURCE = 'COMPILE_SOURCE';
export const SOURCE_COMPILED = 'SOURCE_COMPILED';
export const OUTPUT_SELECTED = 'OUTPUT_SELECTED';
export const SOURCE_SELECTED = 'SOURCE_SELECTED';
